### ISSUE TITLE
No documentation for storage.backends.gs?

### ISSUE THREAD

**Issue by dcgoss** [jschneier/django-storages#126]
I find it quite odd that there is a major storage backend completely left out of the docs. 
While I was searching for a Google Cloud Storage backend for Django, the only one from a reputable repo appeared to be with the [apache-libcloud](http://djangostorages.readthedocs.org/en/latest/backends/apache_libcloud.html) backend. It took a much deeper investigation to realize that there actually is a GCS backend implemented in django-storages, it's just not mentioned.

There needs to be a doc section on `storages.backends.gs`. I would be willing to make it - it seems that you could copy a lot from the S3Boto docs. One quirk is that to use you must get a interoperability key from the Google Cloud Console.

**Comment by jschneier** [comment]
Docs have been an ongoing source of shame for me. I really need to sit down and write them. Any help you are willing to lend would be _greatly_ appreciated.

**Comment by bigblind** [comment]
Do you by any chance know what values to pass to `GS_ACCESS_KEY_ID`and `GS_SECRET_ACCESS_KEY`? Google's official documentation for using boto with gcs tells me to use their boto authentication plugin. As soon as I get that up and running, I'd love to put my learnings in a documentation section for the gs backend.

**Comment by bigblind** [comment]
I just found out about the interoperability settings, and I think this'll work. Let me set it up for myself, and then I'll write some docs for gs. Can you assign me to this issue so I don't forget?

**Comment by dcgoss** [comment]
Yes, the interoperability keys from Google are what you are looking for. They are designed to emulate the S3 keys in functionality.

**Comment by dummerbd** [comment]
@dcgoss I just went down a similar path as you the last two days. It took a lot of hunting around for a decent django storage backend that supports GCS before I stumbled upon the `gs.py` implementation here. Unfortunately, it uses the S3 interop mode instead of Google's GCP Python library...

I should note that I came across a [decent implementation here](https://github.com/BradWhittington/django-gcloud-storage/blob/412fe79c71c0567f33d6cb442c88b222826c5efe/django_gcloud_storage/__init__.py), but it doesn't seem to be actively developed and I'd prefer to use something living in this project instead.

Anyways, you would be interested in the conversation over at PR #236. Basically, the current `gs.py` implementation uses GCS's S3 interop mode which is not meant for production or long term use. It looks like that PR is close to merging... I'm eagerly waiting :)

**Comment by dcgoss** [comment]
@dummerbd I guess I have been ignoring that the interop is not for long term/prod because I didn't want to roll my own/find a different library. Haven't checked back in on this in a while so excited to see that #236 is active, definitely seems like going with the official Google libraries is the smart choice. Will try to take a look if I can

**Comment by jschneier** [comment]
Merged #236. You can use either that new backend or the old libcloud backend.

**Comment by eracle** [comment]
To anyone that randomly ends up on this closed issue, please, check this [stack overflow](https://stackoverflow.com/questions/34247702/configure-django-and-google-cloud-storage/) question.

**Comment by martey** [comment]
@eracle, I'm not sure how helpful that StackOverflow question is, since the majority of answers there - including the accepted one - are out of date.

I think people would be better served by using the `gcloud` backend that replaced the `gs` backend (the pull request that added it, #236, is mentioned several times in the comments above yours). Its documentation is at https://github.com/jschneier/django-storages/blob/master/docs/backends/gcloud.rst.
