### ISSUE TITLE
Add support for AWS S3 Transfer Acceleration

### ISSUE THREAD

**Issue by anderspetersson** [jschneier/django-storages#144]
https://docs.aws.amazon.com/AmazonS3/latest/dev/transfer-acceleration.html

**Comment by jschneier** [comment]
I'd like to support this. We'd need to do this in S3Boto3, not the regular boto and it can't be part of the create bucket call. I [asked on the bugtracker](https://github.com/boto/boto3/issues/823) and it is what it is. If you'd like you can open a PR but otherwise I'm not 100% sure if it's worth polluting the codebase.

**Comment by lifenautjoe** [comment]
Any clue anyone on how to do this?
