### ISSUE TITLE
--clear clears the content of entire s3 bucket

### ISSUE THREAD

**Issue by annamalaissh** [jschneier/django-storages#359]
Hi,
I am using django-storages 1.6.3 and tried to use `python manage.py collectstatic --clear` . It deleted the contents of the entire s3 bucket rather than just deleting the already copied static files. This results in deletion of other valuable resources inside the bucket. Is there some setting that can prevent this from happening ?

**Comment by sww314** [comment]
@annamalaissh I think the preferred workaround is to use a separate bucket for static files. #436 has a workaround to clear by hand.

**Comment by WhyNotHugo** [comment]
`--clear` always deletes all files, that's by design.

When you run `collectstatic`, django copies static files into a directory.

When you run `collecstatic --clear` at a later time, django has no way of knowing which files are statics from the previous run, and which files you put there manually. There's just no way of telling them apart.
