### ISSUE TITLE
Boto3 Support

### ISSUE THREAD

**Issue by mvanderlinde** [jschneier/django-storages#57]
About a week ago, a new version of Boto was released. This new version fixes a number of shortcomings we've encountered with the current version of Boto, so it would be great to see this implemented into django-storages!

https://aws.amazon.com/blogs/aws/now-available-aws-sdk-for-python-3-boto3/

**Comment by jschneier** [comment]
Yeah I saw this as well. I didn't realize it was a total ground up rewrite of boto with a completely different architectural perspective. I'll need to take a better look into what code can be shared and what needs to be changed. Getting this done is up there on my priority list.

**Comment by mbarrien** [comment]
FWIW, I have a quick and dirty and completely untested version of a s3boto3 module I created at https://github.com/mbarrien/django-storages/commit/7a2af530e0c14e4830641fd305da961bf68f0cbe

There's a *lot* of conceptual changes, and the Boto3 library does not completely replace all of Boto 2 (Especially with respect to custom URLs), so there's some hacks to try to get it to work, and a pull request I have out to fix a bug I ran into with presigned URLs. While there's a lot of shared code, I don't think it's worth attempting to share the code between the boto2 and boto3 backends long term because of the conceptual differences woven throughout.

To see what exactly was done, just diff s3boto.py and s3boto3.py. Once again, I warn that it's untested and I haven't even run it myself, just did a quick and dirty attempt at a port.

**Comment by mbarrien** [comment]
FYI, I've now made #111 from a derivative of the branch mentioned here, and I believe it ready to be reviewed now. It's been run in production for several months now.

**Comment by mrgaolei** [comment]
+1

**Comment by darkowic** [comment]
+1

**Comment by jschneier** [comment]
Added in #179.
