### ISSUE TITLE
Could you add S3.py into it.

### ISSUE THREAD

**Issue by cx44yale** [jschneier/django-storages#65]
Right now:

from S3 import CallingFormat
AWS_CALLING_FORMAT = CallingFormat.SUBDOMAIN

This does not work.

**Comment by HiddenFox** [comment]
In the document "http://django-storages.readthedocs.org/en/latest/backends/amazon-S3.html", it says that we can use DEFAULT_FILE_STORAGE = 'storages.backends.s3.S3Storage' or DEFAULT_FILE_STORAGE = 'storages.backends.s3boto.S3BotoStorage'.
But I found that there is no "storages.backends.s3.py" any more.

So I think that you can try to use "storages.backends.s3boto.S3BotoStorage" and "AWS_S3_CALLING_FORMAT" is set to SubdomainCallingFormat by default, which you can see in "https://github.com/jschneier/django-storages/blob/master/storages/backends/s3boto.py" line 228.

**Comment by jschneier** [comment]
Sorry, I guess maybe I should just rename this repository to "django-storages-redux". I had to fork the original django-storages because it was never maintained or updated and the original `backends.s3` was removed. It was marked as deprecated in the original library and I deleted it. If you look at the [CHANGELOG](https://github.com/jschneier/django-storages/blob/master/CHANGELOG.rst) you can see that I did a last release to PyPI of everything in master of the original repository as a version 1.1.9, I wanted to create as little friction as possible for people moving but it appears to have sewn a great deal of confusion.

Let me know if you still have any other questions.
