### ISSUE TITLE
Random google storage images expiry not working

### ISSUE THREAD

**Issue by andrewfam** [jschneier/django-storages#651]
https://www.dataprotectionmgmt.com/

I'm noticing that for some of my users using Chrome, even after the image expires, the url does not update and leaves a blank image there. Using 1.7.1 

![0105ae10-27d2-4067-9c46-ff227d1c3214](https://user-images.githubusercontent.com/1430616/51293107-3f17c280-1a48-11e9-9d01-9aa054751f6e.jpg)

**Comment by andrewfam** [comment]
Is there anything I'm doing wrong? The expiry has been set to the default option.

**Comment by sww314** [comment]
The URL will expire after 1 day (that is the default.)
If you reload the page you should get a new URL. 
You have to make sure you not caching anything, because the if the HTML page is cached, then it url will not update.  

For static images I would not set an expiration, just set those files as public. 

Personally, I typically use [WhiteNoise](http://whitenoise.evans.io/en/stable/) for serving static files and only bother with storages for dynamic media files.
