### ISSUE TITLE
dropbox.stone_validators.ValidationError

### ISSUE THREAD

**Issue by jhondoedo** [jschneier/django-storages#689]
**setting.py**

```
DEFAULT_FILE_STORAGE = 'storages.backends.dropbox.DropBoxStorage'
DROPBOX_OAUTH2_TOKEN = 'token'
DROPBOX_ROOT_PATH = '/media/'
```

**model.py**

```
logo = models.ImageField(upload_to=r'logo/%Y/%m/')
image = models.ImageField(upload_to=r'photos/%Y/%m/',
 help_text='Image size: Width=1080 pixel. Height=1920 pixel',)
```

**error**

Request Method: | POST

Request URL: | http://127.0.0.1:8000/add

Django Version: | 2.1.8

Exception Type: | ValidationError

Exception Value: | 'D:/media/10506738_10150004552801856_220367501106153455_o.jpg' did not match pattern '(/(.\|[\r\n])*\|id:.*)\|(rev:[0-9a-f]{9,})\|(ns:[0-9]+(/.*)?)'

**console**

dropbox.stone_validators.ValidationError: 'D:/media/10506738_10150004552801856_220367501106153455_o.jpg' did not match pattern '(/(.|[\r\n])*|id:.*)|(rev:[0-9a-f]{9,})|(ns:[0-9]+(/.*)?)'

@ZuluPro I can't figure out why this error is happening?  Is the current Dropbox API compatible ?

**Comment by jschneier** [comment]
You seem to be uploading the full path of the file rather than just the name. I can tell because you have the drive `D:/` starting in the beginning. If you want to do that you need to give a valid path for Dropbox to store it and one starting with a Window style drive clearly isn't given the regex of the validation error.

**Comment by johnvorsten** [comment]
@jschneier I ran into this error and I think I found the cause.  django.utils._os.safe_join is used in the DropBoxStorage class _full_path method.  The safe_join method from django prefixes a drive letter to the file path even if you pass a unix style name.

I modified the _full_path method to check if the user is on a windows system in my own fork.  Should I send a pull request?  I've got it working on my own setup, but I have not fully tested everything

**Comment by jschneier** [comment]
Sure.

**Comment by jemuelfontila123** [comment]
@johnvorsten how? do you have any screenshots? i am facing the same issue 
'D:/myapp/media/photos/17635272_1483849838300791_8812826464395385933_o.jpg' did not match pattern '(/(.|[\r\n])*|id:.*)|(rev:[0-9a-f]{9,})|(ns:[0-9]+(/.*)?)'

**Comment by johnvorsten** [comment]
@jemuelfontila123 check out the pull request I just made https://github.com/jschneier/django-storages/pull/875
The problems comes from django.utils.safe_join → it uses os.path.abspath() which prefixes a drive letter to the passed path.  I don't remember the specifics of how I found this out because the path is modified at a few locations in django.core.files.storage and storages.backends.dropbox
