### ISSUE TITLE
Performance of the url() method

### ISSUE THREAD

**Issue by avorio** [jschneier/django-storages#692]
Hi there,

I'm wondering if there's a performance opportunity around the `url()` method used in templates, views, etc., to get the full URL of an Image stored in, say, Amazon S3. It seems to me that the storage engine will do much more than simply put together the file `name` and `MEDIA_URL`.

When I'm dealing with publicly-accessible items on S3, would I be better off simply putting those two values together instead of calling the `url()` method?

I'm using Django REST Framework and need to list 100+ images' URLs in one single request, which is currently heavy via the `url()` method — that was my motivator to try accessing these values directly.

What am I missing?

Many thanks!

**Comment by avorio** [comment]
Anyone?

**Comment by sww314** [comment]
@avorio I typically use Google storage and it has been optimized for public files. 
Unless you tell the storage that all the files are going to be Public, it has to make a round trip to AWS to check permissions, so it is going to be slow.

**Comment by henriquesalvaro** [comment]
I've experienced this same issue recently (mostly due to generating different image sizes + thumbnails), endpoints were significantly (~10x) slower regardless of any prefetch related shenanigans attempted.

As a quick fix I've simply implemented custom serializers to build the URLs with the bucket url + file names, e.g., `f'{settings.DEFAULT_BUCKET_URL}/{instance.file.name}`. 
The next step was extending the `S3Boto3Storage` class and overriding its `url(...)` method.

Building the URL straight on the serializer ended up in better performance than overriding the `S3Boto3Storage` class though.

**Comment by jdmueller** [comment]
I was having trouble figuring this one out. I came up with a solution using something similar.

To make this easier for anyone else I created a package for pip with these mods:
https://pypi.org/project/sorl-thumbnail-jdmueller/

And just add these to settings.py:
MEDIA_URL = "https://" + os.environ.get("AWS_STORAGE_BUCKET_NAME", "bucket-name") + ".s3.amazonaws.com/"
THUMBNAIL_FAST_URL = True

**Comment by wodCZ** [comment]
In it's [current implementation](https://github.com/jschneier/django-storages/blob/master/storages/backends/s3boto3.py#L602-L607) it seems that specifying `AWS_S3_CUSTOM_DOMAIN` (to bucket domain name) skips any unnecessary communication and basically returns the formatted url immediately, while respecting custom location and file name normalization.

**Comment by pmabres** [comment]
This is a naive implementation of how we can bypass any checks to gcloud for example
We can also avoid even initializing gcloud storage like this.
````python
from django.core.exceptions import SuspiciousOperation
from django.core.files.storage import Storage
from django.utils.encoding import smart_str
from storages.utils import (
	clean_name, setting,
	safe_join)

class CloudStorage(Storage):
	bucket_path = setting('GS_BUCKET_PATH')
	file_name_charset = setting('GS_FILE_NAME_CHARSET', 'utf-8')
	location = setting('GS_LOCATION', '')
	settings = None

	@property
	def manager(self):
		if self._manager is None:
			from storages.backends.gcloud import GoogleCloudStorage
			self._manager = GoogleCloudStorage(**self.settings)
		return self._manager

	def __init__(self, **settings):
		self.settings = settings
		self._manager = None

	def _normalize_name(self, name):
		try:
			return safe_join(self.location, name)
		except ValueError:
			raise SuspiciousOperation("Attempted access to '%s' denied." %
									  name)

	def _encode_name(self, name):
		return smart_str(name, encoding=self.file_name_charset)

	def url(self, name):
		if self.bucket_path is not None:
			name = self._encode_name(self._normalize_name(clean_name(name)))
			full_name = self.bucket_path + name
			return full_name
		return self.manager.url(name)

	def _open(self, name, mode='rb'):
		return self.manager._open(name, mode)
	def _save(self, name, content):
		return self.manager._save(name, content)
	def delete(self, name):
		return self.manager.delete(name)
	def exists(self, name):
		return self.manager.exists(name)
	def listdir(self, name):
		return self.manager.listdir(name)
	def size(self, name):
		return self.manager.size(name)
	def get_modified_time(self, name):
		return self.manager.get_modified_time(name)
	def get_created_time(self, name):
		return self.manager.get_created_time(name)
	def get_available_name(self, name, max_length=None):
		return self.manager.get_available_name(name, max_length)
````

**Comment by uhbif19** [comment]
@jdmueller I do not understand how your solution works, could you explain please?

Looks like you use FileSystemStorage to form urls, but I am not sure why this should work - is not it some different Storage at all?

https://github.com/jdmueller/sorl-thumbnail-jdmueller/commit/0f4d1f787d7f29647965a8d3ff3cad92dccb45f9#diff-e3d22d454c3df40ff35f95407205e56def3713e2dd9351768179f406cd2b2cf1L83

**Comment by uhbif19** [comment]
Since my app have not only public, but also private files, I just add some caching for urls.

Solution is not properly tested, but it works and makes endpoints fast.

```
from django.core.cache import cache

from storages.backends.s3boto3 import S3Boto3Storage


class S3Storage(S3Boto3Storage):
    """Storage where signed URLs are cached."""

    def url(self, name, *args):
        normalized_name = self._normalize_name(self._clean_name(name))
        cached_url = cache.get(normalized_name)
        if cached_url is not None:
            return cached_url
        else:
            url = super().url(name, args)
            cache.add(normalized_name, url, self.querystring_expire)
            return url
```

**Comment by sww314** [comment]
@uhbif19 the caching is good solution. However, you want to cache the urls less time that they are valid. Your example code as written can return a url that will expire before it is used. 

I typically cache for half the life of the url. If the URLs are valid for 24 hours then cache the link for 12. The actual values depend on your use case.

**Comment by uhbif19** [comment]
@uhbif19

Thanks for comment. Yes, I thought about this as well as of cache warming.

Why that 12 hours difference would be useful? I thought that it would be enough to add a couple of seconds to compensate the difference between the time link was generated and time it was added to cache.

**Comment by Raduan77** [comment]
Hey, we face a similar issue of bad performance when trying to get URLs for a lot of objects at once. After checking what happens, the sentry shows us that we are trying to retrieve an URL for every object. And for every such object, it is going to CloudFront and is making the HEAD requests. That's the case even if we have turned off the querystring_auth parameter. This is strange because according to the [version we are using](https://github.com/jschneier/django-storages/blob/1.10.1/storages/backends/s3boto3.py#L568), it shouldn't be making any requests at all and should be just forming the URL. Maybe there are some other under the hood things going on, which I am missing. It would be great if you can point me out where the HTTP HEAD requests might be happening.

But, overall, are there any ideas on how performance for a lot(50+) objects in a single request can be improved? I am looking into the direction of these things:
* https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/private-content-signed-cookies.html
* https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/private-content-creating-signed-url-custom-policy.html

But I am not 100% sure if such solutions are compatible with this library. If someone already encountered such an issue and has tackled it, it would be great if you can share!

**Comment by wodCZ** [comment]
The code causing the requests is [here](https://github.com/jschneier/django-storages/blob/master/storages/backends/s3boto3.py#L558-L582).

Defining `AWS_S3_CUSTOM_DOMAIN` makes it run through the *fast branch*. I haven't tried it in combination with `AWS_CLOUDFRONT_KEY_ID`, but it looks like then the url is signed locally using RSA, which should be faster than making HTTP request for each file.

**Comment by uhbif19** [comment]
@Raduan77 Сan you explain how you made Sentry capture this? 

> After checking what happens, the sentry shows us that we are trying to retrieve an URL for every object.

**Comment by Raduan77** [comment]
@wodCZ, thanks for pointing it out.
It seems like we are already using `AWS_CLOUDFRONT_KEY_ID` and `AWS_CLOUDFRONT_KEY`, and it still performs the requests.
Regarding your comment about bucket – we have `AWS_S3_CUSTOM_DOMAIN` defined, so that shouldn't be the case, I believe, since as you've mentioned, it is going through the fast route and doesn't need to perform [these lines](https://github.com/jschneier/django-storages/blob/master/storages/backends/s3boto3.py#L575-L582) 

---
@uhbif19, we haven't done any specific things. Sentry is tracking every transaction by default in our service. After that, you can check every transaction on the `Performance` page. I am adding a screenshot of how it looks.
![Screenshot 2021-05-03 at 15 42 24](https://user-images.githubusercontent.com/36044389/116877591-d2c82980-ac26-11eb-959d-258347de60e1.png)

**Comment by inerte** [comment]
I noticed today I am getting the same effect. In my case at first I noticed in https://scoutapm.com/ that there are HEAD requests going out for each one of my images in a template:

<img width="1474" alt="Screen Shot 2022-01-07 at 5 52 33 PM" src="https://user-images.githubusercontent.com/35285/148626990-bd09d86b-57fc-42bd-aa87-c9ab0f9e293a.png">

Interestingly, I also have Sentry installed (but I was only using it for Errors), so I also decided to check its Performance tab and I can also see the HEAD requests. It does show a bit more than @Raduan77 's screenshot, perhaps a newer version has more details. I can see it's calling `aws.s3.HeadObject`.

I edited the `url` method of `s3boto3.py` to add a few `print`s and I can confirm I have a `custom_domain` and it's returning the `url` earlier. So, something else is making the call.

Also of note is that I have 2 image loops in my template, each one for all images, and I only see HEAD requests for the number of images. In other words, I have 5 images, and 2 loops using `.url` in the template, and I only see 5 head requests.

So I think this rules our the `.url` method. I am still not sure what's generating the HEAD requests. There's [some documentation at boto3 saying](https://github.com/boto/boto3/blob/0b82bf9843ad6d350b48442c47f4a484a886ee3f/docs/source/guide/collections.rst) `HeadObject` will be called if filtering buckets but I don't see django-storages doing any of that.

Will try debug this more later.

**Comment by inerte** [comment]
Okay, maybe storages is doing indirectly through the django's `BaseStorage` - boto3 [docs in Filtering say](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/collections.html?highlight=filtering#filtering):

> Behind the scenes, the above example will call ``ListBuckets``, ``ListObjects``, and ``HeadObject`` many times.

Looking for where `Prefix` is used in storages, it's in `listdir`: https://github.com/jschneier/django-storages/blob/cf50a22d76f1ab3294e85c0a753a7c369663b293/storages/backends/s3boto3.py#L483

But storages never call `listdir` itself, and I can't find exactly where Django itself would call the storages one.

So that's my best guess for now, somehow storages' `listdir` is being called, and filtering Buckets, which makes boto3 call `HeadObject` - but I am really having a hard time reproducing any of this as of now. Hopefully I will have more later.

**Comment by inerte** [comment]
Alright! I have more data. It's **not** `url` (as suspected before), it's `height` (or `width`) on an image. Check the stacktrace, Django's `._get_image_dimensions` ends up calling storages `.open`, which invokes boto3 and `_make_api_call` from `botocore/client.py` is getting called with HEAD:

<img width="1470" alt="Screen Shot 2022-01-09 at 3 37 15 PM" src="https://user-images.githubusercontent.com/35285/148706155-8a00de4d-0195-40d7-9acd-ee8a08f9742d.png">

The solution is simple, don't call `.height` nor `.image` directly from an [ImageField](https://docs.djangoproject.com/en/4.0/ref/models/fields/#django.db.models.ImageField), but use its `height_field` and `width_field` and always use that instead - interestingly, I did have those 2 fields, but was mistakenly calling the ImageField methods.

Sorry for so many messages, as I really wanted to fix this. I could feel some of my pages being slow and I couldn't figure out why, once I saw the `HEAD` requests going out, it led me to this thread and the rabbit hole. My site feels _snappy_ now, a page with 5 images was taking ~2.5 seconds to load, and now ~600ms. Yay!

**Comment by aaronn** [comment]
I'm not sure if this is the same issue, but I'm running into an issue where the ImageField's `update_dimension_fields` is being called hundreds of times on a single request:

<img width="611" alt="Screenshot 2023-02-26 at 6 46 31 PM" src="https://user-images.githubusercontent.com/1653630/221461541-ed690f45-76c8-48c2-9b12-d44fa13b6f55.png">

I've tried to avoid calling `instance.image.url` and instead have opted to call `instance.image.name` and build the url manually as suggested, but it doesn't seem to be working.

Any ideas if this is related to the same thing?

**Comment by DataGreed** [comment]
I've recently started using django-storages with s3 on my new project on django 4.2 and I am running in massive performance issues, especially when listing lots of URL. Very noticable compared to the default django backend.
Is there a workaround for this? I tried disabling `querystring_auth`, but it didn't seem to make much (if any) difference at all

**Comment by pmabres** [comment]
@DataGreed did you try the override class I suggested above? I remember a few years ago we were having issues with non-signed urls and that was the workaround.

https://github.com/jschneier/django-storages/issues/692#issuecomment-593190649

**Comment by DataGreed** [comment]
Interestingly enough, it goes through unsigned connection ,but still adds >200ms of overhead and lists available resources through boto for some reason

![Screenshot 2024-08-12 at 03 39 15](https://github.com/user-attachments/assets/a44f9faa-832a-449e-a4ad-f9cbbc4eeecd)

**Comment by DataGreed** [comment]
@pmabres oh, for some reason I thought something like this was already fixed and merged. No, I haven't tried it, will try. Although, I expected this to work out of the box, I don't really see how the s3 storage backend can be usable for serving file urls via Django if it always communicates with S3.

**Comment by jschneier** [comment]
Hi, do you mind filing a new ticket if you have a new question? The initial issue here was an upstream problem in Django.

**Comment by DataGreed** [comment]
I ended a somewhat absurd solution: I just sat STORAGES.[backend].OPTIONS.custom_domain` to `[my_bycket].s3.amazonaws.com` and it stopped spamming with requests.

@jschneier  Although, I think its very strange that the library actually makes this requests. What is the purpose of that? Can we just disable them or at least have an option to disable them? I don't see what purpose they serve.

**Comment by DataGreed** [comment]
@jschneier sure, sorry I didn't see your response before I posted.
