### ISSUE TITLE
Upload Large File to S3

### ISSUE THREAD

**Issue by steverecio** [jschneier/django-storages#712]
Has anyone integrated the S3Boto3Storage backend with a direct to s3 upload? I'm currently chunking uploads to an EFS drive with the https://github.com/juliomalegria/django-chunked-upload library and then asyncronously using django-storages to commit the file to s3. However, the EFS drive latency is incredibly slow, even with provisioned throughput.

Does anyone have any experience mixing this library with in-browser direct to s3 uploads? Alternatively, has anyone managed to use this library with a file chunking API? I can't simply append to the FileField since s3 doesn't support append operations.

**Comment by jschneier** [comment]
What I have personally done is used Amazon Cognito to do the direct from browser uploading and then post to the backend to create a file with the proper url (you need to do some validation on the url that is posted).

In my case I had to upload many, many files rather than an extremely large one so the logic I had to write was different. The library you linked seems neat though.
