### ISSUE TITLE
Is there a way to put prefixes in filenames? (AWS S3)

### ISSUE THREAD

**Issue by funcho** [jschneier/django-storages#742]
I'd like to config (or override some method) each filename to save in AWS S3 with prefixes (e.g.: model name  + Id). Is there a way to do it?

**Comment by jschneier** [comment]
You can set `upload_to` on your model field to be a callback. Something like

```python
def _profile_pic_location(instance, filename):
    """Create path for image here."""

class MyModel(models.Model):
    picture = models.ImageField(upload_to=_profile_pic_location)
```

**NOTE**: Your `instance.pk` will be `None` if you are creating the object at the same time because the row does not exist yet. The work around is to create the object first and then save the image. More info in [this Stack Overflow answer](https://stackoverflow.com/a/7846812).
