### ISSUE TITLE
Add support for azure-storage-blob>=12.0.0

### ISSUE THREAD

**Issue by larserikgk** [jschneier/django-storages#784]
Yesterday version 12.0.0 of [`azure-storage-blob`](https://github.com/Azure/azure-sdk-for-python/releases/tag/azure-storage-blob_12.0.0) was released.

First of all I would like to request pinning versions of required libraries so new releases of these do not instantly break django-storages if they have any breaking changes. In my opinion it is much better to pin the requirements and update manually when needed/requested.

My nightly build using django-storages for Azure failed, and the first issue I found was the renaming of `BlobPermissions` to `BlobSasPermissions`. This must be updated in [azure_storage.py](https://github.com/jschneier/django-storages/blob/master/storages/backends/azure_storage.py#L8)

I have not looked through the rest of the changes yet, but there might be more issues hidden in the release notes. I will try to find the issues and submit a PR.

An immediate quick fix would be to pin `azure-storage-blob` to version `2.1.0`. The [`azure`] module uses `1.3.1`, so that is an option as well.

Release notes for azure-storage-blob 12.0.0:
* [12.0.0](https://github.com/Azure/azure-sdk-for-python/releases/tag/azure-storage-blob_12.0.0)
* [12.0.0b4](https://github.com/Azure/azure-sdk-for-python/releases/tag/azure-storage-blob_12.0.0b4)
* [12.0.0b3](https://github.com/Azure/azure-sdk-for-python/releases/tag/azure-storage-blob_12.0.0b3)
* [12.0.0b2](https://github.com/Azure/azure-sdk-for-python/releases/tag/azure-storage-blob_12.0.0b2)
* [12.0.0b1](https://github.com/Azure/azure-sdk-for-python/releases/tag/azure-storage-blob_12.0.0b1)

**Comment by Bastien-Brd** [comment]
+1 👍

**Comment by larserikgk** [comment]
There are more changes than just renaming, so I suggest a requirement pin until someone has time to update the code according to 12.0.0 of [azure-storage-blob]. Please see #785

**Comment by jschneier** [comment]
Yeah, many changes. For now I will just pin to `>1.3.1<2.1`. I'm not a fan of pinning altogether.

**Comment by jschneier** [comment]
Sorry, let me clarify. Since most things (this library excepted) now use semantic versioning I think that pinning to version ranges is acceptable, spinning to specific versions is not though.

I'm a bit surprised at how much churn this in the relevant libraries for django-storages.

**Comment by matthewgdv** [comment]
Any progress on this? I'm currently using a wrapper library for `azure-storage-blob` at work that's written for the new version (`>=12.0.0`), and unfortunately installing `django-storages` downgrades `azure-storage-blob`, killing the wrapper. I realize this dependency collision can be dealt with using venvs, but I don't have full control of the environment, so it's not really an option in this case.

**Comment by LordGordonQ** [comment]
Any hope to have `azure-storage-blob>=12.0.0`? Lot of features missing in the old `2.1.0` (such as the new `ContainerClient` class to work with containers).

**Comment by lmmentel** [comment]
It seems that #805 is ready to be merged, any chance of giving this some priority?

**Comment by lmmentel** [comment]
@jschneier would you be able to provide some information on what are the chances to get this finished? I would very much like to use django-storages and even put dev time to keep it up but if for some reason this is not moving forward I'll need to find an alternative which I'm not too excited about. Again I appreciate all the great work so far and hope you can provide a comment about what's needed to close this. Thanks!

**Comment by lodeagcf** [comment]
@lmmentel It's not ideal, but you can use the branch in #805 PR from @pjsier with latest Azure Storage Blob package, by adding following to your requirements.txt:
```
azure-storage-blob==12.8.1
git+https://github.com/pjsier/django-storages.git@update-azure-storage#egg=django-storages[azure]
```
Just make sure to unset `AZURE_CONNECTION_STRING` in your configs, because the format is completely different between what is implemented in #805 -- where it's [a URL to a container](https://github.com/pjsier/django-storages/blob/fb519de50b136dbdff37d72e8c564099c0aa088e/storages/backends/azure_storage.py#L157) -- and what is implemented in vanilla django-storages where it's [an input to BlockBlobService](https://github.com/jschneier/django-storages/blob/35d0b84a488007501ea1d04732f3edf774546055/storages/backends/azure_storage.py#L186) in a legacy format (described [here](https://docs.microsoft.com/en-us/azure/storage/common/storage-configure-connection-string)). 

Once I unset `AZURE_CONNECTION_STRING`, the changes made in #805 were good to go.

**Comment by jschneier** [comment]
There will be another release shortly. I can’t promise more because I will inevitably break it.

Thanks for your patience.

**Comment by lmmentel** [comment]
Thanks @lodeagcf, this is more or less what I'm doing although this is less that ideal for many reasons, I would like to pin package versions instead of relying on a branch form a fork ... The added complexity of installing packages from git instead of pypi also raises concerns.

@jschneier thanks for the response and the news about the release are great but could you say something about this specific issue and if it'll make it? As I said I'm willing to help out getting this fixed, just let me know what you think needs to get done.

**Comment by Ikszad** [comment]
@lodeagcf Hello, I am having trouble with your solution.
I am using poetry to install the dependencies you suggested.

```
django-storages = {git = "https://github.com/pjsier/django-storages.git", rev = "update-azure-storage"}
azure-storage-blob = "12.8.1"
```
And getting import error on BlobPermission

`ImportError: cannot import name 'BlobPermissions' from 'azure.storage.blob' (/home/duser/.cache/pypoetry/virtualenvs/project_env/lib/python3.9/site-packages/azure/storage/blob/__init__.py)`
Any suggestions?
