### ISSUE TITLE
Take over django-storages on PyPI

### ISSUE THREAD

**Issue by jaap3** [jschneier/django-storages#90]
It would be nice if this "fork" became the official django-storages package on PyPI. It's possible to get access to the PyPI package by filing a support ticket at http://sourceforge.net/p/pypi/support-requests/

This is assuming you've contacted the original maintainer of the package with no success.

**Comment by davidbgk** [comment]
> This is assuming you've contacted the original maintainer of the package with no success.

Which might be the case and sorry @jschneier if I didn't answer, my inbox is a mess :-)

Anyway, I can give you access to the PyPI account without any problem, I'm trying to escape the maintenance burden of that repository! My main issue being that I don't use Django anymore… and testing each storage with an access to the underlying service is time-consuming.

@jezdez seems to be OK with that too: https://twitter.com/jezdez/status/690574264550952961

@IanLewis what do you think?

**Comment by jschneier** [comment]
@davidbgk: That'd be great! I did email but it was at the very beginning, no worries :-)

I've been trying to figure out how best to go about testing storages with oh so many providers but it's a headache.

**Comment by IanLewis** [comment]
SGTM

**Comment by mliudev** [comment]
:+1: I have an additional issue that would be solved by having this take over as the official django-storages PyPI package. Consider the scenario where package 'ds-dep' depends on django-storages as part setup.py and you want to use django-storages-redux. If you have django-storages-redux listed before ds-dep then pip will install django-storages-redux, install the dependencies for ds-dep, and then install ds-dep. However, since django-storages-redux does not meet the requirements for django-storages, which ds-dep depends on, it will be overwritten by the PyPI django-storages package. This can lead to subtle and confusing bugs.

There are two ways to get around this currently, neither of which is desirable. First you could list django-storages-redux AFTER ds-dep which will overwrite the python site-packages/storages folder. This results in the correct backends getting used. The second method is to use the '-e' method and ensure the egg is named django-storages. This is more desirable since subsequent dependencies of django-storages will see that it has been satisfied. The down side is you are now pulling from github instead of PyPI.

**Comment by jschneier** [comment]
@mliudev thanks for explaining that.

I was just granted access to the django-storages package on PyPI yesterday and have made it a priority of mine to start using that. My hope is to release a 1.4 with that change this weekend.

**Comment by jschneier** [comment]
Done. Thanks @davidbgk et al for making this package and for blessing this fork.

**Comment by davidbgk** [comment]
Great!
